CREATE ROLE STREAMLIT;
GRANT ROLE STREAMLIT TO USER STREAMLIT;
GRANT ROLE STREAMLIT TO ROLE SYSADMIN;

-- permissions
GRANT IMPORTED PRIVILEGES ON DATABASE CRUNCHBASE_BASIC_COMPANY_DATA TO ROLE STREAMLIT;
GRANT USAGE ON WAREHOUSE REPORTING_XS TO ROLE STREAMLIT;
